manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: sofle-nice-shield
      url-base: https://github.com/SzCsaba01
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: sofle-nice-shield
      remote: SzCsaba01
      revision: main
  self:
    path: config
